[package]
name = "flatzinc"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "A flatzinc parser"
readme = "README.md"
categories = ["parser-implementations"]
documentation = "https://docs.rs/flatzinc"
repository = "https://github.com/sthiele/flatzinc-parser"
license = "MIT"
edition = "2018"
exclude = ["/.github"]

[dependencies]
nom = "5.1"
structopt = "0.3"
anyhow = "1.0"