[package]
name = "flatzinc"
version = "0.3.16"
publish = true
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "A FlatZinc parser"
readme = "README.md"
categories = ["parser-implementations"]
documentation = "https://docs.rs/flatzinc"
repository = "https://github.com/potassco/flatzinc"
license = "MIT"
edition = "2018"
exclude = ["/.github"]

[dependencies]
nom = "6.1"
structopt = "0.3"
anyhow = "1.0"
log = "0.4"
stderrlog = "0.5"
